### PR TITLE
Just use doc comments instead of the doc attribute in the changelog e…

### PR DESCRIPTION
**Pull request by weiznich**
This just looks more like rust code in this way.

(And yes this is just working)

### CODE REVIEW

**Comment by theduke** [comment]
The tests are there for a reason... ;)

Also, the object macro docs should still show the `#[doc]` variant.

There are valid situations where you'd want to use that instead.

**Comment by weiznich** [comment]
I've fixed the tests. (There were just some whitespace issues 😉 ). I've also included a hint to the docs that doc attributes are also supported.

The CI failures seems to be caused by a dependency that does not support the minimal supported rustc version.

**Comment by kestred** [comment]
Oh this actually works?!  😅

**Comment by weiznich** [comment]
@kestred Doc comments are basically identical to using the doc attribute in this case. See [the documentation](https://doc.rust-lang.org/beta/rustdoc/the-doc-attribute.html) for more information.

**Comment by weiznich** [comment]
@theduke @LegNeato any news on this?

**Comment by LegNeato** [comment]
I'm trying to get CI back up using precompiled binaries from https://github.com/sagiegurari/cargo-make/pull/127.

**Comment by LegNeato** [comment]
Actually, I see all the tests pass on other builders so I'll just land while I wrestle with CI.

**Pull request merged**
