### PR TITLE
Fix helper macros for 2018 edition.

### PR DESCRIPTION
**Pull request by theduke**
Fixes #298

### CODE REVIEW

**Comment by LegNeato** [comment]
Should we have an integration test that uses the 2018 edition to make sure we don't regress again here?

**Comment by theduke** [comment]
@LegNeato exactly what I thought.

**Comment by theduke** [comment]
I refactored the macros now to use the $crate:: method instead of local_inner_macro.

**Comment by LegNeato** [comment]
Do we want to release a patch to 0.11? If so we should probably not use $crate as to not bump the min version. I'm not a stickler for semver so would also be willing to just push a point release and be done with it so we don't have to republish all the other crates. 🤷‍♂️

**Comment by theduke** [comment]
Yeah I'd say we just retroactively say that 0.11 requires 1.30+.
We officially only support the current release - 2 anyway, so that works out fine. 

I'd just really like to find a fix for the custom derive issue that's not so awkward.
I found one but that only works on 1.32+. :/

**Comment by theduke** [comment]
Alright, it's done!

A explanation of the fix is in the commit message: https://github.com/graphql-rust/juniper/pull/298/commits/7b2b6e9f3df0c9978c970565dec8b8938b6e165a

**Comment by theduke** [comment]
Added a VERY minimal 2018 edition test.

**Pull request merged**
