### PR TITLE
Refactor to 2018 edition + some clippy fixes

### PR DESCRIPTION
**Pull request by theduke**
Note this also bumps the minimum version to `1.31`, which fits with our "last 3 versions" rule though since 1.34 is out.

### CODE REVIEW

**Comment by theduke** [comment]
Hmm now the introspection queries are broken on nightly!

Very weird, will investigate.

**Comment by theduke** [comment]
The diff is seriously screwed up on nightly but fine on stable.

No idea what's happening here. 

https://gist.github.com/theduke/186359a930abb2f172cb9b59c7a037fc

**Comment by LegNeato** [comment]
I bet you this is due to the new `std` hashmap implementation. These tests probably assume a hashmap ordering? I thought we weren't using the standard hashmap and were instead relying on indexmap everywhere.

**Comment by LegNeato** [comment]
Actually, might not directly be the new `HashMap`. This error:

```
---- tests::introspection_tests::test_introspection_directives stdout ----
thread 'tests::introspection_tests::test_introspection_directives' panicked at 'assertion failed: `(left == right)`
  left: `(Object(Object { key_value_list: [("__schema", Object(Object { key_value_list: [("directives", List([Object(Object { key_value_list: [("name", Scalar(String("include"))), ("locations", List([Scalar(String("FIELD")), Scalar(String("FRAGMENT_SPREAD")), Scalar(String("INLINE_FRAGMENT"))]))] }), Object(Object { key_value_list: [("name", Scalar(String("skip"))), ("locations", List([Scalar(String("FIELD")), Scalar(String("FRAGMENT_SPREAD")), Scalar(String("INLINE_FRAGMENT"))]))] })]))] }))] }), [])`,

 right: `(Object(Object { key_value_list: [("__schema", Object(Object { key_value_list: [("directives", List([Object(Object { key_value_list: [("name", Scalar(String("skip"))), ("locations", List([Scalar(String("FIELD")), Scalar(String("FRAGMENT_SPREAD")), Scalar(String("INLINE_FRAGMENT"))]))] }), Object(Object { key_value_list: [("name", Scalar(String("include"))), ("locations", List([Scalar(String("FIELD")), Scalar(String("FRAGMENT_SPREAD")), Scalar(String("INLINE_FRAGMENT"))]))] })]))] }))] }), [])`',
```

Shows that `key_value_list`, which is a `Vec`, now has items in a different order. `Vec` sort order should be stable...

**Comment by theduke** [comment]
We still use HashMap for the type and directive registry.

**Comment by LegNeato** [comment]
I just read somewhere that there is a MIR ordering regression. Can't find the bug though.

**Pull request merged**
