### PR TITLE
Redesign `GraphQLScalar` macros

### PR DESCRIPTION
**Pull request by ilslv**
Part of #1010

## Synopsis

Main goal of this PR is to support generic scalars.

## Solution

In addition to this PR tries to unify `#[graphql_scalar]` and `#[derive(GraphQLScalar)]` macros. This is done by introducing ability to use custom resolvers: 

```rust
#[derive(GraphQLScalar)]
#[graphql(to_output_with = Self::to_output)]
struct Scalar(i32);

impl Scalar {
    fn to_output(&self) -> Value {
        Value::scalar(self.0 + 1)
    }
}
```

But we can't remove `#[graphql_scalar]` macro entirely because of uncovered use-case of derive macro: types from other crate

```rust
#[graphql_scalar(
    with = object_id,
    parse_token = String,
    scalar = LocalScalarValue,
)]
type ObjectId = bson::oid::ObjectId;

mod object_id {
    use super::*;

    pub(super) type Error = String;

    pub(super) fn to_output(v: &ObjectId) -> Value<LocalScalarValue> {
        Value::scalar(v.to_hex())
    }

    pub(super) fn from_input(v: &InputValue<LocalScalarValue>) -> Result<ObjectId, Error> {
        v.as_string_value()
            .ok_or_else(|| format!("Expected `String`, found: {}", v))
            .and_then(|s| {
                ObjectId::parse_str(s).map_err(|e| format!("Failed to parse `ObjectId`: {}", e))
            })
    }
}
```

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
## FCM

```
- Redesign `#[derive(GraphQLScalar)]` and `#[graphql_scalar]` macros (#1017)
  - `#[derive(GraphQLScalar)]`
    - support generic scalars
    - support structs with single named field
    - support for overriding resolvers
  - `#[graphql_scalar]`
    - use on type aliases only in case `#[derive(GraphQLScalar)]` isn't applicable because of orphan rule
```

**Comment by ilslv** [comment]
@tyranron at the end I've decided not to split PRs for derive and attribute macros, because built-in scalar implementation are looking better with both macros present:

```rust
#[derive(Clone, Debug, Eq, GraphQLScalar, PartialEq, Serialize, Deserialize)]
#[graphql(with = id, parse_token(String, i32))]
pub struct ID(String);

mod id {
    use super::*;

    pub(super) type Error = String;

    pub(super) fn to_output<S: ScalarValue>(v: &ID) -> Value<S> {
        Value::scalar(v.0.clone())
    }

    pub(super) fn from_input<S: ScalarValue>(v: &InputValue<S>) -> Result<ID, Error> {
        v.as_string_value()
            .map(str::to_owned)
            .or_else(|| v.as_int_value().map(|i| i.to_string()))
            .map(ID)
            .ok_or_else(|| format!("Expected `String` or `Int`, found: {}", v))
    }
}

#[graphql_scalar(with = int)]
type Int = i32;

mod int {
    use super::*;

    pub(super) type Error = String;

    pub(super) fn to_output<S: ScalarValue>(v: &Int) -> Value<S> {
        Value::scalar(*v)
    }

    pub(super) fn from_input<S: ScalarValue>(v: &InputValue<S>) -> Result<Int, Error> {
        v.as_int_value()
            .ok_or_else(|| format!("Expected `Int`, found: {}", v))
    }

    pub(super) fn parse_token<S: ScalarValue>(value: ScalarToken<'_>) -> ParseScalarResult<'_, S> {
        if let ScalarToken::Int(v) = value {
            v.parse()
                .map_err(|_| ParseError::UnexpectedToken(Token::Scalar(value)))
                .map(|s: i32| s.into())
        } else {
            Err(ParseError::UnexpectedToken(Token::Scalar(value)))
        }
    }
}
```

**Review by tyranron — APPROVED** [review]
@ilslv great work, thanks! 🍻

**Comment by rimutaka** [comment]
@ilslv , @tyranron , how final is this change? I saw some rust-docs updates in the diffs, but no book updates. What is the plan with that? I'm happy to help there.

**Comment by tyranron** [comment]
@rimutaka the current Book isn't ideal, but should be up-to-date with these changes on the current `master`. Please, re-check it.

**Pull request merged**
