### PR TITLE
Make operation_name public

### PR DESCRIPTION
**Pull request by cgm616**
See #253.

### CODE REVIEW

**Comment by cgm616** [comment]
Where can I add an integration test? Is there a collection of them already that exists, or should I create a `juniper/tests` directory alongside `src` in that crate?

**Comment by LegNeato** [comment]
I think the `tests` directory is the way to go. You'll need to use [`GraphQLRequest::new()`](https://github.com/graphql-rust/juniper/blob/fd636e07df99744d9964570991bba3ff283f6642/juniper/src/http/mod.rs#L46) and then call `operation_name()`. If it is private (that is, we undo this change), the integration test should then fail to compile.

Let me know if you run into any issues!

**Comment by LegNeato** [comment]
@cgm616 Thank you very much! As soon as CI goes green I will merge.

**Comment by LegNeato** [comment]
🎉

**Pull request merged**
