### PR TITLE
Added usage of context validator in the async executor

### PR DESCRIPTION
**Pull request by engylemure**
This PR is intended to add the validation of the requested document in the async executor.

### CODE REVIEW

**Comment by LegNeato** [comment]
Hmmm, I thought we had a test for this?

**Comment by engylemure** [comment]
I will write a small one in the async await integration test

**Comment by LegNeato** [comment]
Just need to run `cargo fmt`.

**Comment by LegNeato** [comment]
Thanks a lot! 🥂

**Pull request merged**
