### PR TITLE
WIP: Add authorization to juniper.

### PR DESCRIPTION
**Pull request by AurelienFT**
WIP

### CODE REVIEW

**Comment by LegNeato** [comment]
I am not sure we would take a PR to do this. For example, this assumes a certain structure of a permission system which may not work for all apps.

What is stopping you from doing this on top of juniper? Why not wrap juniper `objects` and such so that your authorization code is called by the resolver?

**Comment by EituKo** [comment]
`What is stopping you from doing this on top of juniper? Why not wrap juniper objects and such so that your authorization code is called by the resolver?`
This is what we were planning to do, but I don't quite understand how we could implement this without a PR. Can you provide us some pseudo code to help us comprehend?

**Comment by andy128k** [comment]
@EituKo Resolvers can return an error (`FieldResult<...>`).

```rust
#[juniper::object(context = MyContext)]
impl Query {
    fn protected_field(mycontext: &MyContext) -> FieldResult<YourTypeHere> {
         if context.authorize() {
              Ok(/* your code here */)
         } else {
              Err("Access denied".to_string())
         }
    }
}
```

**Comment by LegNeato** [comment]
As @andy128k points out, can you can call whatever you want in the resolvers. You would manually something similar to above for each field you need auth. If that is repetitive you can create your own macros or derives with your own annotations.

For example, you could create a macro `myauth_graphql_object:`:

```rust
#[myauth_graphql_object(context = MyContext)]
impl Query {
    #[myauth(protected)]
    fn protected_field(mycontext: &MyContext) -> YourTypeHere {
     // your protected code here
    }
    fn unprotected_field(mycontext: &MyContext) -> YourTypeHere {
     // your unprotected code here
    }
}
```
That would spit out:
```rust
#[juniper::object(context = MyContext)]
impl Query {
    fn protected_field(mycontext: &MyContext) -> FieldResult<YourTypeHere> {
         if context.authorize() {
              Ok(/* your protected code here */)
         } else {
              Err("Access denied".to_string())
         }
    }

    fn unprotected_field(mycontext: &MyContext) -> YourTypeHere {
         /* your unprotected code here */)
    }
}
```

(probably best to make it protected by default in a real implementation though to prevent security bugs).

Note the generated `FieldResult` and if statement due to the `myauth` annotation.

Here `myauth_graphql_object` is a [procedural macro](https://doc.rust-lang.org/reference/procedural-macros.html). I'm not sure if proc macros are multiple passes so if you can directly generate the call to`juniper::graphql_object`. If not your auth macro can depend on `juniper_codegen` and just output the juniper boilerplate directly. 

You could add whatever you want in there and generate whatever code makes sense for you.

Let me know if this doesn't solve the issue!

**Pull request closed without merging**
