### PR TITLE
chrono feature: Implement GraphQLType for chrono::NaiveDate and chrono::DateTime

### PR DESCRIPTION
**Pull request by LegNeato**
Fixes https://github.com/graphql-rust/juniper/issues/87

### CODE REVIEW

**Comment by passcod** [comment]
I'd just like to note that JSON numbers (i.e. IEEE doubles) are not precise enough for nanosecond datetimes expressed as timestamps. They're precise enough for up to microsecond resolution.

**Comment by theduke** [comment]
@passcod I'm aware of the tradeoff, do you personally see that as a problem though?

I'd reckon microsecond resolution would be sufficient for most use cases, which this intends to cover. Most times used in a context were GraphQL is used tend to be only second resolution anyway in my experience.

**Comment by passcod** [comment]
Ah, no, I mean it should be noted in the documentation, so that _users_ are aware of the tradeoff.

**Comment by LegNeato** [comment]
Added the additional types and serialization + docs.

**Comment by mhallin** [comment]
This looks very nice, thank you!

**Pull request merged**
