### PR TITLE
Add release automation

### PR DESCRIPTION
**Pull request by LegNeato**
See `RELEASING.md` for directions

### CODE REVIEW

**Comment by LegNeato** [comment]
Largely fixes https://github.com/graphql-rust/juniper/issues/248

**Comment by theduke** [comment]
This looks great.

**Comment by theduke** [comment]
```
[cargo-make] INFO - Task: release-dry-run
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: release-dry-run
[cargo-make] INFO - Execute Command: "cargo" "make" "release-dry-run-INTERNAL"
[cargo-make] INFO - cargo make 0.18.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: release-dry-run-INTERNAL
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: workspace
[cargo-make] INFO - cargo make 0.18.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: release-dry-run-INTERNAL
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: release-dry-run-INTERNAL
[cargo-make] INFO - Execute Command: "cargo-release" "release" "--config" "../_build/release.toml" "--dry-run" "patch"
Update to version 0.11.2 and commit
Fatal: IO Error: No such file or directory (os error 2)
[cargo-make] ERROR - Error while executing command, exit code: 128
[cargo-make] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by LegNeato** [comment]
Where are you running it from? It needs to be run from the workspace root currently

**Comment by theduke** [comment]
Running from the root.

**Comment by LegNeato** [comment]
Ok, will take a look. Also I'll add the dry run to CI

**Comment by LegNeato** [comment]
Sweet, everything looks like it is working!

**Pull request merged**
