### PR TITLE
juniper_rocket: make request limit configurable

### PR DESCRIPTION
**Pull request by toxeus**
Before, it was not possible to set a different request body size limit. Now, the configurable limit value from Rocket's `Limits` struct [1] is obtained with a fallback to the hardcoded value in case no value has been configured.

[1] https://api.rocket.rs/master/rocket/data/struct.Limits.html

I'm running into the hardcoded limit now and therefore would really appreciate if a release of juniper_rocket could be made after this has been merged.

### CODE REVIEW

**Comment by toxeus** [comment]
@tyranron @LegNeato is anything missing in this PR?

**Review by tyranron — APPROVED** [review]
@toxeus thanks 🍻. Will be released soon.

**Comment by tyranron** [comment]
@toxeus released in [0.8.1 `juniper_rocket`](https://crates.io/crates/juniper_rocket/0.8.1).

**Comment by toxeus** [comment]
Thank you @tyranron!

**Pull request merged**
