### PR TITLE
Add support for the canonical introspection query

### PR DESCRIPTION
**Pull request by LegNeato**
Fixes https://github.com/graphql-rust/juniper/issues/307.

I also fixed all the book tests to run and I am too lazy to put them in a different PR 🤷‍♂️

### CODE REVIEW

**Comment by theduke** [comment]
:+1: 

LGTM

**Comment by theduke** [comment]
@LegNeato actually, why do we need the with description / no description split?

**Comment by LegNeato** [comment]
@theduke I don't know, I just followed what graphqljs did. I would imagine it is probably for space savings?

**Comment by LegNeato** [comment]
@theduke confirmed with the GraphQL.js team that it to save data/space when the result is read by a machine. If the target is a dev tool that wants descriptions then you include them, but if the target is a code generator that doesn't need them then you can save the download bytes.

**Pull request merged**
