### PR TITLE
Clean up clippy warnings remove try!

### LINKED ISSUE #131: Clean up Clippy warnings + remove try!
Right now, there are a lot of clippy warnings in the codebase.

Most of them are sensible suggestions and should be fixed.

Also, we should remove `try!` and replace it with   `?` everywhere.

Instructions:

```bash
rustup install nightly
rustup default nightly
cargo install clippy

cd juniper
cargo clippy
```

This is an easy task and help is very welcome.
@LegNeato

### PR DESCRIPTION
**Pull request by Atul9**
closes #131

### CODE REVIEW

**Comment by theduke** [comment]
@Atul9 do you need help with figuring out the errors?

**Comment by Atul9** [comment]
@theduke Yes, I need help with figuring out the build failures. I had mentioned this on the issue https://github.com/graphql-rust/juniper/issues/131#issuecomment-361048391

**Comment by neoeinstein** [comment]
@Atul9 I added a PR to Atul9/juniper#1 which should correct the build errors.

**Comment by theduke** [comment]
@Atul9 @neoeinstein thanks a bunch to you both, that was quite a bite of work.

**Comment by theduke** [comment]
@neoeinstein also thanks for the detailed commit messages. ;)

**Pull request merged**
