### PR TITLE
Executor.schema(&self) is kind of useless without declaring SchemaTyp…

### PR DESCRIPTION
**Pull request by jadedevin13**
…e as public

### CODE REVIEW

**Comment by jadedevin13** [comment]
This is also useful if you want to search the concrete_type_by_name when using lookaheads.

**Comment by LegNeato** [comment]
Thanks for the PR!

**Comment by LegNeato** [comment]
Awesome, thanks again! 🍻

**Comment by jadedevin13** [comment]
Thanks. Awesome crate. More power!

**Pull request merged**
