### PR TITLE
upgrade iron  to 0.6

### PR DESCRIPTION
**Pull request by Matrix-Zhang**

### CODE REVIEW

**Comment by theduke** [comment]
@Matrix-Zhang I assume `0.6` contains breaking changes?

If so, can you: 
* bump the crate version to 0.2 in Cargo.toml 
* add information in CHANGELOG.md
?

**Comment by Matrix-Zhang** [comment]
i have fixed..

**Comment by qguv** [comment]
Excited to see this come down the line!

**Comment by theduke** [comment]
Merged with #142

**Comment by theduke** [comment]
@Matrix-Zhang @qguv published to crates.io as `0.1.2` since it's not a breaking change.
Sorry for the delay.

**Pull request closed without merging**
