### PR TITLE
Attempt first naive version of async union

### PR DESCRIPTION
**Pull request by xla**
This addreses #549 as we ran into the lack of support for unions when trying to migrate to `async/await`. **This is a severe case of i-have-no-clue what I'm doing.** As mostly inspired by the enum implementation copy-pastad code at the moment, I look very much for feedback on how to make the async support proper and according to the standards of the crate. So don't go easy here, thanks.

### CODE REVIEW

**Comment by LegNeato** [comment]
It looks likes the tests are failing

**Comment by arlyon** [comment]
All the tests pass on my machine with a small change to a lifetime:

```rust
diff --git a/juniper/src/macros/tests/union.rs b/juniper/src/macros/tests/union.rs
index 6dfbfe75..089ea3b2 100644
--- a/juniper/src/macros/tests/union.rs
+++ b/juniper/src/macros/tests/union.rs
@@ -57,7 +57,7 @@ impl CustomName {
 }
 
 #[crate::graphql_union_internal]
-impl<'a> WithLifetime<'a> {
+impl<'b> WithLifetime<'b> {
     fn resolve(&self) {
         match self {
             Concrete => match *self {
```

**Comment by LegNeato** [comment]
I'll have to look more later, but one should be able to name lifetimes whatever. So likely the macro generated lifetime needs to have a name like '__a to avoid conflicts.

**Comment by LegNeato** [comment]
Also note some union tests are turned off:

https://github.com/graphql-rust/juniper/blob/6e4bc127b05dc29f7832cbf468c9fb2bc18f78ec/juniper/src/executor_tests/mod.rs#L7

They need to be turned back on and pass.

**Pull request closed without merging**
