### PR TITLE
Switch to HashMap for the internal representation of object fields

### PR DESCRIPTION
**Pull request by abrackx**
Hey there, first time contributing here. 

This PR updates Object's field key_value_list to use a `HashMap<String, Value<S>>` (#818).

Because HashMaps are unordered I had problems with a few tests that were saving values as strings and then comparing to other expected strings. The tests `object_query`, `display_object` and `batch_requests_work` were examples of that. I resolved these failures by doing some json object comparison but I'm not sure if that's the best approach. 

I am also not sure if I need to update the changelog for this so please let me know. 

I'll put this as a draft in case I completely missed the mark.

### CODE REVIEW

**Comment by LegNeato** [comment]
Sorry this took so long, this looks great! We have benchmarks in https://github.com/graphql-rust/juniper/tree/master/juniper_benchmarks, can you see if this improves or regresses?

**Comment by LegNeato** [comment]
Note that the GraphQL specification requires result field order to stay the same as query field order...it might be best to use `IndexMap` here to preserve ordering. That will likely make the tests work as-is (assuming the issue is ordering).

Thank you again for the PR! 🍻

**Review by LegNeato — CHANGES_REQUESTED** [review]
Let's preserve order.

**Comment by abrackx** [comment]
Updated! IndexMap seemed to do the trick. 

I ran benchmarks on master, checked out this branch and then reran them. Here is the output: 
[after.txt](https://github.com/graphql-rust/juniper/files/6058142/after.txt) 

It looks like performance improved on `Sync vs Async - Users Flat - Instant/Sync/1` and `Sync vs Async - Users Flat - Instant/Async - Single Thread/10`. Otherwise performance did not change.

Let me know if there's anything else I missed. Thanks!

**Review by LegNeato — APPROVED** [review]

**Comment by LegNeato** [comment]
Thank you for the change!  🍻

Sorry again it too so long to take a look at it, and welcome to Juniper!

**Comment by LegNeato** [comment]
This is now on crates.io. Thank you again!

**Pull request merged**
