### PR TITLE
Fix List input coercion rules

### PR DESCRIPTION
**Pull request by ilslv**
## Synopsis

For now, `[Int]!` and `[Int!]!` can accept `Null` which contradicts [GraphQL Spec](https://spec.graphql.org/October2021/#sec-Combining-List-and-Non-Null).

## Solution

Forbid coercing `null`s into non-null lists, while allowing for now coercing `[1, 2, 3]` into `[[Int]]` (resulting in `[[1], [2], [3]]`), because this may be an ambiguity error: https://github.com/graphql/graphql-spec/pull/515

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
## FCM

```
Fix List input coercion rules (#1004)
```

**Comment by ilslv** [comment]
## FCM

```
Fix List input coercion rules (#1004)
```

**Comment by ilslv** [comment]
`wasm` builds are broken now because of the `bson` `2.1.0` version

- https://github.com/mongodb/bson-rust/issues/334

**Review by tyranron — APPROVED** [review]
@ilslv 👍

**Pull request merged**
