### PR TITLE
Make juniper_hyper functions return `Response<Body>` where applicable

### PR DESCRIPTION
**Pull request by samuela**
Fix https://github.com/graphql-rust/juniper/issues/881.

Changes juniper_hyper to return `Response<Body>` instead of `Result<Response<Body>, hyper::Error>` for:
* `graphql`
* `graphql_sync`
* `graphiql`
* `playground`

Feel free to let me know if I'm missing any others!

### CODE REVIEW

**Comment by samuela** [comment]
Test failures don't seem to be related.

**Review by LegNeato — APPROVED** [review]

**Comment by LegNeato** [comment]
Thank you! 🍻

**Comment by LegNeato** [comment]
This is now on crates.io. Thank you again!

**Comment by samuela** [comment]
Sweet, thanks @LegNeato!

**Pull request merged**
