### PR TITLE
Fragment spreads in Interface types

### LINKED ISSUE #407: Panic when using fragment of a implementation in a interface
**Describe the bug**
Juniper panic when using a fragment for an implementation directly in a interface.

**To Reproduce**
```rust
use juniper::*;

struct Query;

#[juniper::object]
impl Query {
    fn things() -> Vec<Thing> {
        vec![Thing::Foo(Foo { foo: 1 }), Thing::Bar(Bar { bar: 2 })]
    }
}

enum Thing {
    Foo(Foo),
    Bar(Bar),
}

juniper::graphql_interface!(Thing: () where Scalar = <S> |&self| {
    instance_resolvers: |_| {
        &Foo => match *self { Thing::Foo(ref foo) => Some(foo), _ => None },
        &Bar => match *self { Thing::Bar(ref bar) => Some(bar), _ => None },
    }
});

struct Foo {
    foo: i32,
}

#[juniper::object(
    interfaces = [&Thing],
    scalar = S
)]
impl<S: ScalarValue> Foo {
    fn foo(&self) -> i32 {
        self.foo
    }
}

struct Bar {
    bar: i32,
}

#[juniper::object(
    interfaces = [&Thing],
    scalar = S
)]
impl<S: ScalarValue> Bar {
    fn bar(&self) -> i32 {
        self.bar
    }
}

type Schema = juniper::RootNode<'static, Query, EmptyMutation<()>>;

#[test]
fn test_fragment_in_interface_does_not_work() {
    let _ = juniper::execute(
        r#"
            query Query {
                things {
                    ...fooFields
                    ...barFields
                }
            }

            fragment fooFields on Foo {
                foo
            }

            fragment barFields on Bar {
                bar
            }
        "#,
        None,
        &Schema::new(Query, EmptyMutation::new()),
        &Variables::new(),
        &(),
    )
    .unwrap();
}

#[test]
fn test_fragment_in_interface_works() {
    let _ = juniper::execute(
        r#"
            query Query {
                things {
                    ...on Foo {
                        ...fooFields
                    }
                    ...on Bar {
                        ...barFields
                    }
                }
            }

            fragment fooFields on Foo {
                foo
            }

            fragment barFields on Bar {
                bar
            }
        "#,
        None,
        &Schema::new(Query, EmptyMutation::new()),
        &Variables::new(),
        &(),
    )
    .unwrap();
}
```

Error:
`thread 'fragment_in_interface::test_fragment_in_interface_does_not_work' panicked at 'Field foo not found on type Some("Thing")', juniper\src\types\base.rs:385:21`

**Expected behavior**
Both queries should be equivalent.

### PR DESCRIPTION
**Pull request by dyedgreen**
Closes #407

### CODE REVIEW

**Comment by dyedgreen** [comment]
As a note: I'm not sure if there is a difference between the `async` and sync type resolution which I'm missing with this. The tests I added are async, so the fix might miss out on the sync case of this bug (if it exists).

**Comment by tyranron** [comment]
@dyedgreen thanks for the contribution!

Actually, yes. The sync execution is implemented separately (it has similar name and flow). So, it would be nice to provide a fix for it too and cover it with tests.

**Review by LegNeato — APPROVED** [review]
Thank you so much for the PR and including tests! 🍻

**Comment by LegNeato** [comment]
This is now on crates.io. Thank you again!

**Pull request merged**
