### PR TITLE
Update testing juniper::http::mod

### PR DESCRIPTION
**Pull request by Jekshmek**
Added a missing post test method with variables and made a valid get method test_duplicate_keys and fix run testing.

### CODE REVIEW

**Comment by LegNeato** [comment]
Thanks for the PR! Looks great, can you rebase to get CI working?

**Comment by Jekshmek** [comment]
@LegNeato Tell me to understand, if you remove the duplicate key, it is still not the correct syntax!
```rust
// /?query={"query": "{hero{name}}"}
let response = integration.get("/?query=%7B%22query%22%3A%20%22%7Bhero%7Bname%7D%7D%22%7D");
assert_eq!(response.status_code, 400);
```

```rust
Is the URL correct for checking for duplicate key?
// /?query={hero{blah}}&query={hero{blah}}
let response = integration.get("/?query=%7Bhero%7Bblah%7D%7D&query=%7Bhero%7Bblah%7D%7D"); 
```
p.s. The `Hyper` integration does not check the key duplication by the current url, since the code block does not work at all responsible for this, as does `Iron`. They give the correct result for other reasons not related to the current test.

**Comment by LegNeato** [comment]
Hmmm, not sure. It's been a while since I looked at this harness.

**Comment by Jekshmek** [comment]
@LegNeato I think that 
```/?query = {"query": "{hero {name}}", "query": "{hero {name}}"}```
 this URL checks the correctness of the graphql query syntax but not the duplicate key, meaning not controlling truncation of data

**Pull request closed without merging**
