### PR TITLE
Preserve the order of requested fields

### PR DESCRIPTION
**Pull request by LegNeato**
Fixes https://github.com/graphql-rust/juniper/issues/82

Note: I am new to Rust, please let me know if there is anything I can do better.

### CODE REVIEW

**Comment by theduke** [comment]
Since the spec recommends it, I'm definitely in favor.

There are two open questions for me:

* what is the performance impact of linked-hash-map vs Hashmap?

* I'm not so comfortable with bringing in https://github.com/contain-rs/linked-hash-map as a dependency
  The README states:
  WARNING: THIS PROJECT IS IN MAINTENANCE MODE, DUE TO INSUFFICIENT MAINTAINER RESOURCES

**Comment by LegNeato** [comment]
Re: perf, I couldn't get `cargo bench` to work locally...any pointers would be appreciated.

Re: `linked-hash-map`, I was hesitant as well.  https://github.com/bluss/ordermap looks better maintained but doesn't yet have serde support (https://github.com/bluss/ordermap/pull/28) which `juniper` needs. Also, `linked-hash-map` maintainers said they will merge changes to keep it compatible and building...which I think is all we really need for juniper in the future. I intend to keep an eye on `ordermap` and switch if/when it has serde support.

**Comment by rushmorem** [comment]
Can't we switch to OrderMap and use [remote derive](https://serde.rs/remote-derive.html) for now?

**Comment by LegNeato** [comment]
I just tried and it doesn't look like you can use remote derive for this, as just using

```rust
#[derive(Serialize, Deserialize)]
#[serde(remote = "OrderMap")]
```
Fails as the default derive isn't sufficent and 

```rust
#[serde(remote = "OrderMap")]
```
fails without `derive()`.

I'm a Rust n00b, so if there is a way to do this that I am missing please let me know!

**Comment by LegNeato** [comment]
Also, I am not sure but https://github.com/bluss/ordermap/issues/19 might cause some issues here too. I'd prefer to merge this as-is (assuming perf is ok), as I don't think switching in the future will be that big of a pain for users (but I could be wrong!).

**Comment by LegNeato** [comment]
I got them to do a release, so latest changes use `ordermap`.

**Comment by bluss** [comment]
Nice to see that you get some utility out of ordermap. As a point of order, you'll should probably add Ordermap's 1.0-ing on your own 1.0 road map, since it's a “public dependency” when used like this.

OrderMap itself doesn't have an 1.0 road map, for the record, but the future is open ended.

**Comment by mhallin** [comment]
Thanks for this PR! Bringing us closer to spec compliance :)

**Pull request merged**
