### PR TITLE
Accept Content-Type: application/graphql in web server integrations

### LINKED ISSUE #426: Support Content-Type: application/graphql
**Is your feature request related to a problem? Please describe.**

I'm trying out Juniper + Hyper and discovered that it doesn't support `Content-Type: application/graphql`.

When submitting an HTTP POST request containing a JSON GraphQL query, like so, it works as expected:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"query":"{user(id:\"1\") {name email}}"}' http://localhost:3000/graphql
{
  "data": {
    "user": {
      "name": "name",
      "email": "name@example.com"
    }
  }
}
```

However, other GraphQL implementations also support `Content-Type: application/graphql` where the entire POST body is treated as the GraphQL query. When I tried it with Juniper + Hyper, I get:

```
$ curl -X POST -H "Content-Type: application/graphql" -d '{user(id: "1") {name email}}' http://localhost:3000/graphql
key must be a string at line 1 column 2
```

It seems that Juniper + Hyper is still treating the POST body as JSON and thus encountering a parsing error.

**Describe the solution you'd like**

Juniper + Hyper should accept `Content-Type: application/graphql` and handle it accordingly, similar to a `GET` query.

**Describe alternatives you've considered**

While JSON payloads are more powerful (since you can include variables), `application/graphql` _is_ commonly accepted by other GraphQL implementations in other languages.

**Additional context**

I have a working juniper-hyper project at https://github.com/aisrael/juniper-hyper-demo

### PR DESCRIPTION
**Pull request by sd2k**
When finished, this should fix #426.

Hyper, Iron and Rocket integrations are working fine with tests. I can't for the life of me figure out how to get the warp integration working - any guidance there would be much appreciated!

### CODE REVIEW

**Comment by theduke** [comment]
Hey, thanks.

For warp, you would basically just need to adapt the [warp::body::json](https://docs.rs/warp/0.1.20/src/warp/filters/body.rs.html#163) method.

Something like this should work:

```rust
 ( warp::filters::header::exact(mime::APPLICATION, mime::JSON)
      .or( warp::filters::header::exact(...)
  )
  // Rest of the code of the json() function
  .and (...)
```

**Comment by sd2k** [comment]
@theduke Ah sorry, I _think_ I've managed to get the individual filters to compile fine (`get_filter` remains unchanged, `post_filter` has just been refactored into `post_json_filter`, and there's a new `post_graphql_filter` for handling `Content-Type: application/graphql`. I'm struggling to combine them correctly into a single `BoxedFilter`.

**Comment by tyranron** [comment]
@sd2k why have you closed this? You have no time for finishing this?

**Comment by sd2k** [comment]
@tyranron That's strange, I didn't close it intentionally, I just force rebased my branch on master. I still can't get the `warp` integration working though and don't think I'll have time to do so unfortunately, so if anyone is more experienced in `warp` and wants to take over that would be great.

**Comment by sd2k** [comment]
Ah, I see, I accidentally removed the new commits from my fork when I rebased which closed this PR automatically. Looks like I'll need to create a new PR to get GitHub to recognise the new commits. Happy to do that although the warp changes still won't be there.

**Comment by tyranron** [comment]
@sd2k if you don't mind I'll pick up your work and finish it in a separate PR.

**Comment by sd2k** [comment]
@tyranron fine with me, go ahead :slightly_smiling_face:

**Pull request closed without merging**
