### PR TITLE
Fix typos and add GitHub Action job for /book

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell book/ -L crate`

### CODE REVIEW

**Review by tyranron — CHANGES_REQUESTED** [review]
@kianmeng could you add a `codespell` CI check? Would be nice to have one.

**Comment by kianmeng** [comment]
@tyranron Should we fix all the typo errors in the whole repo before adding the CI job?

**Comment by tyranron** [comment]
@kianmeng let's try and see. I'm not strictly opposed to this.

**Comment by kianmeng** [comment]
@tyranron Sorry for the delay, I've added the GHA, but can't test and validate it from my end.

**Comment by Snoupix** [comment]
@tyranron (up)
Hey, are we far away from 0.16 release ?

**Comment by LegNeato** [comment]
@tyranron Can this be merged? I don't see which changes are outstanding.

**Review by tyranron — APPROVED** [review]
@kianmeng thanks! And sorry for the delay!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
