### PR TITLE
Abstract (start, end) from Spanning struct into new struct Span

### PR DESCRIPTION
**Pull request by audunhalland**
This makes it easier to treat the source region (the Span) separately from the spanned item in `Spanning`.

### CODE REVIEW

**Review by tyranron — CHANGES_REQUESTED** [review]
@audunhalland please, make this PR editable for maintainers:
Screenshot 2023-11-09 at 14 29 45

**Comment by audunhalland** [comment]
The checkbox isn't visible for me. Could it be because the fork is owned by an organization in which I'm not an administrator? :thinking: 

Perhaps it's better if I re-create the PR from my personal fork.

**Comment by audunhalland** [comment]
New PR up at https://github.com/graphql-rust/juniper/pull/1208 (from a my personal fork). Sorry for the noise :crying_cat_face: 

The "Allow edits" github bug is discussed here: https://github.com/orgs/community/discussions/5634

**Comment by tyranron** [comment]
@audunhalland thanks!

**Pull request closed without merging**
