### PR TITLE
windows build fix

### PR DESCRIPTION
**Pull request by sagiegurari**
**please do not merge until both linux and windows builds finish successfully.**

The changes include

* remove the --all-features from the juniper tests
* skip juniper rocket for beta/stable rust channel.
* both appveyor and travis will invoke the exact same flow.

### CODE REVIEW

**Comment by mhallin** [comment]
I'm hesitant to merge this as the big problem with `cargo-make` on Windows was that it didn't fail builds with failing tests. You can see e.g. https://github.com/graphql-rust/juniper/pull/109 - the build log is unfortunately no longer available apparently - but Travis failed (correctly) due to failing tests, while the Appveyor build passed despite having failed tests.

**Comment by sagiegurari** [comment]
I'll try to reproduce on my fork to see if it is still an issue.
I do know of 2 issues on windows which I fixed yesterday (the PR here came only after I did some fixes for windows).

**Comment by sagiegurari** [comment]
Ok, found the issue (too bad wasn't reported earlier) and now it is resolved.
You can see example build:
https://ci.appveyor.com/project/sagiegurari/juniper/build/1.0.14/job/40wxjpbbuc068kg6

**Comment by sagiegurari** [comment]
Interesting but specific platform failed to compile ring 0.11.0 in juniper_rocket. 
Seems in your build script you set it up only for msvc platform. I'll do the needed changes.

**Comment by sagiegurari** [comment]
I see I'll have to work a bit more on it. closing it for now.

**Pull request closed without merging**
